### ISSUE TITLE
the picture can't show out

### ISSUE THREAD

**Issue by xJayLee** [InvertGames/uFrame.Documentation#1]
the picture can't show out. Maybe you guys could create a wiki(git.io)

**Comment by bartlomiejwolk** [comment]
which picture?

**Comment by liudequ** [comment]
Only in the tutorial-1.md pictures can show out .Other tutorial's picture link is wrong.

**Comment by bartlomiejwolk** [comment]
I fixed it now. Thanks for reporting.
